#!/bin/sh

[ -n "$STAR64_EXTLINUX_PKG" ] || exit 0

pacman --noconfirm --disable-sandbox -S --needed dracut
pacman --noconfirm --disable-sandbox -U "/mnt/$STAR64_EXTLINUX_PKG"

# this triggers a hook which sets up extlinux.conf
pacman --noconfirm --disable-sandbox -U "/mnt/$LINUX_PKG"
