#!/bin/sh -e

[ -n "$STAR64_EXTLINUX_PKG" ] || exit 0

pacman --noconfirm --disable-sandbox -S --needed dracut
pacman --noconfirm --disable-sandbox -U "/mnt/$STAR64_EXTLINUX_PKG"

# run once manually
/usr/bin/create_uboot_extlinux_conf
